#!/bin/sh

get_volume_icon () {
    LEVEL=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
    STATUS=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $4 }')
    if [[ $STATUS == "off" ]] then
        ICON=󰝟
    elif [[ $LEVEL < 33 ]] then
        ICON=󰕿
    elif [[ $LEVEL < 66 ]] then
        ICON=
    else
        ICON=󰕾
    fi
    echo " $ICON "
}

toggle() {
    amixer -q set Master toggle
}

if [[ ! $1 ]] then
    amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%'
elif [[ $1 == "icon" ]] then
    get_volume_icon
elif [[ $1 == "toggle" ]] then
    toggle
fi
