#!/bin/sh

toggle() {
    WIFI_ENABLED=$(nmcli radio wifi)
    if [[ $WIFI_ENABLED == "enabled" ]] then
        nmcli radio wifi off
    else
        nmcli radio wifi on
    fi
}

status() {
    WIFI_ENABLED=$(nmcli radio wifi)
    SSID=$(nmcli | grep wlp6s0 | awk 'FNR==1' | awk '{print $4}')
    STATUS=$(nmcli | grep wlp6s0 | awk 'FNR==1' | awk '{print $2}')

    STATUS_ICON=" 󰖪 "
    if [[ $STATUS == "connected" ]] then
        STATUS_ICON=" 󰖩 "
    fi

    ENABLED=false
    if [[ $WIFI_ENABLED == "enabled" ]] then
        ENABLED=true
    fi

    printf '{ "enabled": "%s", "icon": "%s", "ssid": "%s" }\n'  $ENABLED $STATUS_ICON $SSID
}

if [[ $1 == "toggle" ]] then
    toggle
elif [[ $1 == "status" ]] then
    status
fi
