"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true


[character]
success_symbol = "[➜](bold green)"

[username]
show_always = true
style_user = "bold red"
format = '[$user ]($style)'

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold fg:#ef9f76)@[$hostname](bold fg:#ef9f76) "
disabled = false
