#!/bin/sh

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
fi

bar () {
    eww open-many --toggle bar bar2
}

system () {
    eww open --toggle system_menu
}

if [[ $1 == "bar" ]] then
    bar
elif [[ $1 == "system" ]] then
    system
fi
