#!/bin/sh

## Files and cmd
DIR="$HOME/.cache/eww"
FILE="$HOME/.cache/eww/bar"
EWW="eww -c $HOME/.config/eww/bar"

## Create eww cache dir if it does not exist
if [[ ! -d $DIR ]] then
    mkdir -p $DIR
fi

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    rm -r $DIR/*
    ${EWW} daemon
    sleep 1
fi

## Open widgets
run_eww() {
    ${EWW} open-many \
        bar \
        bar2
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
else
    ${EWW} close-all
    rm "$FILE"
fi
