return function()
    vim.keymap.set("n", "<leader>th", function()
        require("harpoon.term").gotoTerminal(1)
    end)
    vim.keymap.set("n", "<leader>tj", function()
        require("harpoon.term").gotoTerminal(2)
    end)
    vim.keymap.set("n", "<leader>tk", function()
        require("harpoon.term").gotoTerminal(3)
    end)

    vim.keymap.set("n", "<C-j>", function()
        require("harpoon.ui").nav_file(1)
    end)
    vim.keymap.set("n", "<C-k>", function()
        require("harpoon.ui").nav_file(2)
    end)
    vim.keymap.set("n", "<leader>ma", function()
        require("harpoon.mark").add_file()
    end)
    vim.keymap.set("n", "<leader>mm", require("harpoon.ui").toggle_quick_menu)
end
