#! /bin/sh
source "${HOME}/.cache/squash/colors"

~/.config/polybar/launch.sh &
pgrep -x dunst > /dev/null || dunst &

bspc monitor DP-2 -d 1 2 3 4
bspc monitor DP-0 -d 5 6 7 8

bspc config border_width         3
bspc config window_gap          20

bspc config split_ratio          0.5

bspc config normal_border_color "${BSPWM_NORMAL}"
bspc config focused_border_color "${BSPWM_FOCUSED}"
