#! /bin/sh

pgrep -x polybar > /dev/null ||  ~/.config/polybar/launch-polybars.sh &
pgrep -x dunst > /dev/null || dunst &

bspc monitor DP-2 -d code web misc misc
bspc monitor DP-0 -d web slack misc misc

bspc config border_width         3
bspc config window_gap          20

bspc config split_ratio          0.5
