#!/bin/sh

get_volume_status () {
    LEVEL=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
    STATUS=$(amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $4 }')
    if [[ $STATUS == "off" ]] then
        ICON=󰝟
    elif [[ $LEVEL < 33 ]] then
        ICON=󰕿
    elif [[ $LEVEL < 66 ]] then
        ICON=
    else
        ICON=󰕾
    fi
    echo " $ICON "
}

toggle() {
    amixer -q set Master toggle
    # if [ $STATUS == "false" ]; then
    #     notify-send --icon=volume-level-muted --urgency=normal "Volume is muted." "Volume has been muted, your PC has been shut the fucked up."
    # else
    #     notify-send --icon=volume-level-high --urgency=normal "Volume has been turned on." "Sound is now on, you will hear farts!"
    # fi
}

if [[ ! $1 ]] then
    amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%'
elif [[ $1 == "status" ]] then
    get_volume_status
elif [[ $1 == "toggle" ]] then
    toggle
fi
