---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider

themes:
  catppuccin:
    bg: [48, 45, 65]
    black: [22, 19, 32]
    blue: [150, 205, 251]
    cyan: [26, 24, 38]
    fg: [217, 224, 238]
    gray: [87, 82, 104]
    green: [171, 233, 179]
    magenta: [245, 194, 231]
    orange: [248, 189, 150]
    red: [242, 143, 173]
    white: [217, 224, 238]
    yellow: [250, 227, 176]

theme: catppuccin

keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
    tab:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 't', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: 'r']
        - action: [GoToPreviousTab,]
          key: [ Char: 'h', Left, Up, Char: 'k',]
        - action: [GoToNextTab,]
          key: [ Char: 'l', Right,Down, Char: 'j']
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'n',]
        - action: [CloseTab, SwitchToMode: Normal,]
          key: [ Char: 'x',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc,]
