---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider

themes:
  catppuccin:
    bg: [48, 45, 65]
    black: [22, 19, 32]
    blue: [150, 205, 251]
    cyan: [26, 24, 38]
    fg: [217, 224, 238]
    gray: [87, 82, 104]
    green: [171, 233, 179]
    magenta: [245, 194, 231]
    orange: [248, 189, 150]
    red: [242, 143, 173]
    white: [217, 224, 238]
    yellow: [250, 227, 176]

theme: catppuccin

keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [NewPane: ]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    pane:
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'b', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [MoveFocus: Left,]
          key: [ Char: 'h', Left,]
        - action: [MoveFocus: Right,]
          key: [ Char: 'l', Right,]
        - action: [MoveFocus: Down,]
          key: [ Char: 'j', Down,]
        - action: [MoveFocus: Up,]
          key: [ Char: 'k', Up,]
        - action: [SwitchFocus,]
          key: [Char: 'p']
        - action: [NewPane: , SwitchToMode: Normal,]
          key: [Char: 'n',]
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: 'd',]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: 'r',]
        - action: [CloseFocus, SwitchToMode: Normal,]
          key: [Char: 'x',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'f',]
        - action: [TogglePaneFrames, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [SwitchToMode: RenamePane, PaneNameInput: [0],]
          key: [Char: 'c']
    move:
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'h', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [MovePane: ,]
          key: [Char: 'n', Char: "\t",]
        - action: [MovePane: Left,]
          key: [Char: 'h', Left,]
        - action: [MovePane: Down,]
          key: [Char: 'j', Down,]
        - action: [MovePane: Up,]
          key: [Char: 'k', Up, ]
        - action: [MovePane: Right,]
          key: [Char: 'l', Right,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    tab:
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 't', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: 'r']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [GoToPreviousTab,]
          key: [ Char: 'h', Left, Up, Char: 'k',]
        - action: [GoToNextTab,]
          key: [ Char: 'l', Right,Down, Char: 'j']
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'n',]
        - action: [CloseTab, SwitchToMode: Normal,]
          key: [ Char: 'x',]
        - action: [ToggleActiveSyncTab, SwitchToMode: Normal,]
          key: [Char: 's']
        - action: [GoToTab: 1, SwitchToMode: Normal,]
          key: [ Char: '1',]
        - action: [GoToTab: 2, SwitchToMode: Normal,]
          key: [ Char: '2',]
        - action: [GoToTab: 3, SwitchToMode: Normal,]
          key: [ Char: '3',]
        - action: [GoToTab: 4, SwitchToMode: Normal,]
          key: [ Char: '4',]
        - action: [GoToTab: 5, SwitchToMode: Normal,]
          key: [ Char: '5',]
        - action: [GoToTab: 6, SwitchToMode: Normal,]
          key: [ Char: '6',]
        - action: [GoToTab: 7, SwitchToMode: Normal,]
          key: [ Char: '7',]
        - action: [GoToTab: 8, SwitchToMode: Normal,]
          key: [ Char: '8',]
        - action: [GoToTab: 9, SwitchToMode: Normal,]
          key: [ Char: '9',]
        - action: [ToggleTab]
          key: [ Char: "\t" ]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    renamepane:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [PaneNameInput: [27] , SwitchToMode: Pane,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    session:
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Detach,]
          key: [Char: 'd',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
