# Generated by matugen - do not edit manually

# Base palette
set -g fish_color_normal "{{dank16.color7.default.hex}}"
set -g fish_color_command "{{dank16.color10.default.hex}}"
set -g fish_color_keyword "{{dank16.color5.default.hex}}"
set -g fish_color_quote "{{dank16.color3.default.hex}}"
set -g fish_color_redirection "{{dank16.color6.default.hex}}"
set -g fish_color_end "{{dank16.color2.default.hex}}"
set -g fish_color_error "{{dank16.color1.default.hex}}"
set -g fish_color_param "{{dank16.color7.default.hex}}"
set -g fish_color_comment "{{dank16.color8.default.hex}}"
set -g fish_color_selection --background="{{dank16.color12.default.hex}}"
set -g fish_color_search_match --background="{{dank16.color13.default.hex}}"
set -g fish_color_operator "{{dank16.color10.default.hex}}"
set -g fish_color_escape "{{dank16.color11.default.hex}}"
set -g fish_color_autosuggestion "{{dank16.color8.default.hex}}"

# Pager colors
set -g fish_pager_color_progress "{{dank16.color6.default.hex}}"
set -g fish_pager_color_prefix "{{dank16.color4.default.hex}}"
set -g fish_pager_color_completion "{{dank16.color7.default.hex}}"
set -g fish_pager_color_description "{{dank16.color8.default.hex}}"
set -g fish_pager_color_secondary_description "{{dank16.color9.default.hex}}"
set -g fish_pager_color_selected_background --background="{{dank16.color12.default.hex}}"
set -g fish_pager_color_selected_prefix "{{dank16.color5.default.hex}}"

function fish_prompt
    set -l last_status $status

    # User
    set_color "{{dank16.color6.default.hex}}"
    echo -n (whoami)

    # Host
    set_color "{{dank16.color14.default.hex}}"
    echo -n "@"
    echo -n (hostname -s)

    # Path
    set_color "{{dank16.color10.default.hex}}"
    echo -n " "
    echo -n (prompt_pwd)

    # Git branch
    if command -sq git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color "{{dank16.color5.default.hex}}"
            echo -n " [$branch]"
        end
    end

    echo -n " "

    # Prompt symbol
    if test $last_status -eq 0
        set_color "{{dank16.color2.default.hex}}"
    else
        set_color "{{dank16.color1.default.hex}}"
    end

    echo -n "> "

    set_color normal
end
