# Automatically generated by Matugen
set -U fish_color_normal {{colors.primary.default.hex}}
set -U fish_color_command {{colors.primary.default.hex}}
set -U fish_color_quote {{colors.secondary.default.hex}}
set -U fish_color_redirection {{colors.tertiary.default.hex}}
set -U fish_color_end {{colors.surface.default.hex}}
set -U fish_color_error {{colors.error.default.hex}}
set -U fish_color_param {{colors.on_primary.default.hex}}
set -U fish_color_comment {{colors.outline.default.hex}}
set -U fish_color_selection --background={{colors.surface_container.default.hex}}
set -U fish_color_search_match --background={{colors.secondary_container.default.hex}}
